// Generated by CoffeeScript 1.7.1
(function() {
  window.SlidePager = (function() {
    function SlidePager(options) {
      this.$body = $("body");
      this.number = 1111;
      this.beforeState = [];
    }

    SlidePager.prototype.shiftLeft = function() {
      if (this.isBack("right")) {
        this.number -= 100;
        this.beforeState.pop();
      } else {
        this.number += 1000;
        this.beforeState.push("left");
      }
      this.$dataname(this.number).addClass("none");
      return this.$body.html(this.beforeState);
    };

    SlidePager.prototype.shiftRight = function() {
      if (this.isBack("left")) {
        this.number -= 1000;
        this.beforeState.pop();
      } else {
        this.number += 100;
        this.beforeState.push("right");
      }
      this.$dataname(this.number).addClass("none");
      return this.$body.html(this.beforeState);
    };

    SlidePager.prototype.shiftUp = function() {
      if (this.isBack("down")) {
        this.number -= 1;
        this.beforeState.pop();
      } else {
        this.number += 10;
        this.beforeState.push("up");
      }
      this.$dataname(this.number).addClass("none");
      return this.$body.html(this.beforeState);
    };

    SlidePager.prototype.shiftDown = function() {
      if (this.isBack("up")) {
        this.number -= 10;
        this.beforeState.pop();
      } else {
        this.number += 1;
        this.beforeState.push("down");
      }
      this.$dataname(this.number).addClass("none");
      return this.$body.html(this.beforeState);
    };

    SlidePager.prototype.$dataname = function(number) {
      return $("[data-js=" + number + "]");
    };

    SlidePager.prototype.isBack = function(latestState) {
      return this.beforeState[this.beforeState.length - 1] === latestState;
    };

    return SlidePager;

  })();

}).call(this);
